INSERT INTO airline (country, name) VALUES
('United States', 'American Airlines'),
('United States', 'Delta Air Lines'),
('United States', 'United Airlines'),
('United States', 'Southwest Airlines'),
('United States', 'Alaska Airlines'),
('United States', 'JetBlue Airways'),
('Canada', 'Air Canada'),
('Canada', 'WestJet'),
('Canada', 'Porter Airlines'),
('Mexico', 'Aeroméxico'),
('Mexico', 'Volaris'),
('Germany', 'Lufthansa'),
('United Kingdom', 'British Airways'),
('France', 'Air France'),
('Netherlands', 'KLM Royal Dutch Airlines');